//有一台设备要运行1整年，每天 00:00和12:00检查一次://
//当温度>30℃，启动降温，启动后先降低3℃并检测温度一次，若≥20℃，再降低3℃并检测一次;若温度<20℃，停止降温;//
//当温度<10℃，启动增温，启动后先增温 2℃并检测温度一次，若<13℃，//
//增温2℃并检测一次，若温度>13℃，停止增温;//
//当温度≥10℃且≤30℃，设备不增降温//
//(每次检查的温度值为-5~40℃的一个随机数)://
